In [55]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore',category=UserWarning)
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [56]:
df=pd.read_csv('C:/Users/shary/Downloads/nnewagrcultuire.csv')

In [57]:
df.head()

       YEARS   DISTRICTS      CROPS RAINFALL  YEILD  PRICE
0  2005-2010  bagalakote     cotton      34%   10.4  10000
1  2011-2015  bagalakote  sugarcane      58%    2.0   3000
2  2016-2020  bagalakote      maize      65%    2.5   4000
3  2005-2010  bagalakote     cotton      26%   10.0   3000
4  2011-2015     ballari     cotton      30%    3.0   4000

In [58]:
df.tail()

        YEARS     DISTRICTS      CROPS RAINFALL  YEILD  PRICE
93  2017-2020      yadagiri    coconut      69%    9.9   2000
94  2006-2009  vijayanagara      paddy      85%    0.7   3000
95  2005-2008  vijayanagara      maize      82%    5.0   4000
96  2010-2020  vijayanagara  betel nut      98%    7.0   5000
97  2022-2025  vijayanagara  sugarcane      74%    4.3   6000

In [59]:
X = df[['RAINFALL','YEARS','DISTRICTS','CROPS']]
y = df[['YEILD','PRICE']]

In [60]:
X

   RAINFALL      YEARS     DISTRICTS      CROPS
0       34%  2005-2010    bagalakote     cotton
1       58%  2011-2015    bagalakote  sugarcane
2       65%  2016-2020    bagalakote      maize
3       26%  2005-2010    bagalakote     cotton
4       30%  2011-2015       ballari     cotton
..      ...        ...           ...        ...
93      69%  2017-2020      yadagiri    coconut
94      85%  2006-2009  vijayanagara      paddy
95      82%  2005-2008  vijayanagara      maize
96      98%  2010-2020  vijayanagara  betel nut
97      74%  2022-2025  vijayanagara  sugarcane

[98 rows x 4 columns]

In [61]:
y

    YEILD  PRICE
0    10.4  10000
1     2.0   3000
2     2.5   4000
3    10.0   3000
4     3.0   4000
..    ...    ...
93    9.9   2000
94    0.7   3000
95    5.0   4000
96    7.0   5000
97    4.3   6000

[98 rows x 2 columns]

In [66]:
X = pd.get_dummies(X)
le = LabelEncoder()

In [67]:
X.head()

,RAINFALL_26%,RAINFALL_30%,RAINFALL_32%,RAINFALL_34%,RAINFALL_35%,RAINFALL_36%,RAINFALL_38%,RAINFALL_39%,RAINFALL_40%,RAINFALL_41%,...,DISTRICTS_vijayapura,DISTRICTS_yadagiri,CROPS_betel nut,CROPS_coconut,CROPS_cotton,CROPS_maize,CROPS_paddy,CROPS_ragi,CROPS_sugarcane,CROPS_vegetables
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [63]:
X_test

   RAINFALL      YEARS        DISTRICTS       CROPS
62      69%  2016-2020           mandya       paddy
40      57%  2011-2015            gadag  vegetables
94      85%  2006-2009     vijayanagara       paddy
18      36%  2005-2010            bidar       paddy
81      44%  2005-2010            udupi  vegetables
83      54%  2016-2020   uttara kannada     coconut
64      41%  2011-2015           mysuru      cotton
42      59%  2005-2010           hasana      cotton
10      70%  2011-2015         belagavi  vegetables
0       34%  2005-2010       bagalakote      cotton
31      42%  2011-2015      chitradurga       maize
75      67%  2005-2010         tumakuru        ragi
47      58%  2016-2020           haveri       maize
26      55%  2016-2020   chikkamagaluru       maize
44      55%  2016-2020           hasana        ragi
4       30%  2011-2015          ballari      cotton
22      53%  2011-2015  chikkaballapura  vegetables
12      65%  2005-2010         belagavi      cotton
90      42%  2005-2010         yadagiri       paddy
73      56%  2011-2015       shivamogga       paddy
49      45%  2011-2015       kalaburagi        ragi
70      45%  2011-2015       ramanagara       paddy
68      43%  2016-2020         raichuru  vegetables
15      41%  2005-2010  bengaluru urban      cotton
39      64%  2005-2010            gadag   betel nut
33      59%  2005-2010      chitradurga       paddy
9       79%  2005-2010         belagavi        ragi
80      34%  2016-2020            udupi       paddy
11      43%  2016-2020         belagavi   sugarcane
65      60%  2016-2020           mysuru   sugarcane

In [64]:
y_test

    YEILD  PRICE
62    3.0   3000
40    9.9   2000
94    0.7   3000
18    3.9   8000
81   10.3   6000
83    4.0   5000
64    8.4  10000
42    5.0   8000
10    2.5   5000
0    10.4  10000
31    4.1   5000
75    3.4   7000
47    2.5   3000
26    2.3   3000
44    4.5   6000
4     3.0   4000
22    4.9   5000
12    4.0   6000
90    2.3   2000
73    2.3   6000
49    9.3  10000
70    9.0  10000
68    2.4   6000
15   10.5   2000
39    4.6   8000
33    2.1   4000
9     5.0   4000
80    8.9   5000
11    3.9   3000
65    1.9   2000

In [70]:
dtc = DecisionTreeClassifier(criterion="entropy", random_state=30)
dtc.fit(X_train, y_train)
y_pred_dt = dtc.predict(X_test)

print("Decision Tree Accuracy:", metrics.accuracy_score(y_test, y_pred_dt))

ValueError: could not convert string to float: '69%'